title: Fra Bunden
description: Mad, alkohol og andet godt, lavet fra bunden
url: "https://frabunden.dk"
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - docs
  - scripts
  - README.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
